[variables]
    NIXPACKS_PHP_VERSION = '8.4'

[phases.setup]
    nixPkgs = ['...', 'php84', 'php84Packages.composer', 'nodejs_20']

[phases.install]
    cmds = ['composer install --ignore-platform-reqs --optimize-autoloader --no-interaction']